INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, E_MAIL) VALUES ('1', 'andrewjkme', '1234', '김종윤', 'andrewjk.me@gmail.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, E_MAIL) VALUES ('2', 'nnguyen', '1234', 'Amy', 'nnguyen457@gmail.com');

INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE, COUNT_OF_ANSWER) VALUES (1, 1, 'test title', 'test contents', CURRENT_TIMESTAMP, 0);
INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE, COUNT_OF_ANSWER) VALUES (2, 2, 'test title2', 'test contents2', CURRENT_TIMESTAMP, 0);
